[licenses]
allow = [
  "MIT",
  "CC0-1.0",
  "ISC",
  "OpenSSL",
  "Unlicense",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Zlib",
]

unlicensed = "warn"
default = "warn"

private = { ignore = true }

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[advisories]
ignore = [
    # term is looking for a new maintainer
    # https://github.com/vectordotdev/vector/issues/6225
    "RUSTSEC-2018-0015",

    # `net2` crate has been deprecated; use `socket2` instead
    # https://github.com/vectordotdev/vector/issues/5582
    "RUSTSEC-2020-0016",

    # Type confusion if __private_get_type_id__ is overridden
    # https://github.com/vectordotdev/vector/issues/5583
    "RUSTSEC-2020-0036",

    # stdweb is unmaintained
    # https://github.com/vectordotdev/vector/issues/5585
    "RUSTSEC-2020-0056",

    # Potential segfault in localtime_r invocations
    # We resolved this by patching chrono to use a version that doesn't depend on `time` v0.1
    # https://github.com/vectordotdev/vector/issues/9679
    "RUSTSEC-2020-0159",
]

[bans]
deny = [
    # https://github.com/vectordotdev/vector/issues/11257
    { name = "tokio-util", version = ">=0.6.9" },
]
