---
data_dir: /vector-data-dir
api:
  enabled: true
  address: "[::]:8686"
  playground: false
sources:
  datadog_agent:
    address: "[::]:8282"
    type: datadog_agent
  fluent:
    address: "[::]:24224"
    type: fluent
  internal_metrics:
    type: internal_metrics
  logstash:
    address: "[::]:5044"
    type: logstash
  splunk_hec:
    address: "[::]:8080"
    type: splunk_hec
  statsd:
    address: "[::]:8125"
    mode: tcp
    type: statsd
  syslog:
    address: "[::]:9000"
    mode: tcp
    type: syslog
  vector:
    address: "[::]:6000"
    type: vector
    version: "2"
sinks:
  prom_exporter:
    type: prometheus_exporter
    inputs:
      - internal_metrics
    address: "[::]:9090"
  blackhole:
    type: blackhole
    inputs:
      - datadog_agent
      - fluent
      - logstash
      - splunk_hec
      - statsd
      - syslog
      - vector
    print_interval_secs: 10
    acknowledgements:
      enabled: true
