data_dir = "/var/lib/vector"

##
## Sources
##

[sources.internal_metrics]
type = "internal_metrics"

[sources.fluent]
type = "fluent"
address = "0.0.0.0:8282"

##
## Transforms
##

[transforms.remap]
type = "remap"
inputs = ["fluent"]
source = """
event = del(.event)
# set event to message fields, dropping any existing fields
. = {}
.event = object!(event)
"""

##
## Sinks
##

[sinks.prometheus]
type = "prometheus_exporter"
inputs = ["internal_metrics"]
address = "0.0.0.0:9090"

[sinks.firehose-sink]
type = "aws_kinesis_firehose"
inputs = ["remap"]
stream_name = "soak_fluent_remap_firehose"
endpoint = "http://localhost:8080"
healthcheck.enabled = true
compression = "none"
encoding = "json"
region = "us-east-2"
auth.access_key_id = "totallyanaccesskeyid"
auth.secret_access_key = "alsoasecretaccesskey"
