---
data_dir: /vector-data-dir
api:
  enabled: true
  address: "[::]:8686"
  playground: false
sources:
  datadog_agent:
    address: "[::1]:8282"
    type: datadog_agent
  file:
    include:
      - "/var/log/**/*.log"
    type: file
    ignore_checkpoints: true
  host_metrics:
    filesystem:
      devices:
        excludes: [binfmt_misc]
      filesystems:
        excludes: [binfmt_misc]
      mountPoints:
        excludes: ["*/proc/sys/fs/binfmt_misc"]
    type: host_metrics
  internal_metrics:
    type: internal_metrics
  logstash:
    address: "[::1]:5044"
    type: logstash
sinks:
  prom_exporter:
    type: prometheus_exporter
    inputs:
      - host_metrics
      - internal_metrics
    address: "[::]:9090"
  blackhole:
    type: blackhole
    inputs:
      - datadog_agent
      - file
      - logstash
    print_interval_secs: 10
    acknowledgements:
      enabled: true
