---
data_dir: /vector-data-dir
api:
  enabled: true
  address: "[::]:8686"
  playground: false
sources:
  kubernetes_logs:
    type: kubernetes_logs
  host_metrics:
    filesystem:
      devices:
        excludes: [binfmt_misc]
      filesystems:
        excludes: [binfmt_misc]
      mountPoints:
        excludes: ["*/proc/sys/fs/binfmt_misc"]
    type: host_metrics
  internal_metrics:
    type: internal_metrics
sinks:
  prom_exporter:
    type: prometheus_exporter
    inputs:
      - host_metrics
      - internal_metrics
    address: "[::]:9090"
  blackhole:
    type: blackhole
    inputs:
      - kubernetes_logs
    print_interval_secs: 10
    acknowledgements:
      enabled: true
