version: "3"

services:
  postgres:
    image: docker.io/postgres:13.1
    command: /postgres-init.sh
    environment:
      - POSTGRES_USER=vector
      - POSTGRES_PASSWORD=vector
    volumes:
      - socket:/var/run/postgresql
      - ${PWD}/tests/data/postgres-init.sh:/postgres-init.sh:ro
      - ${PWD}/tests/data:/certs:ro
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "postgresql_metrics-integration-tests"
      - "--lib"
      - "${FILTER:-::postgres}"
      - "--"
      - "--nocapture"
    depends_on:
      - postgres
    environment:
      - PG_SOCKET=/socket
      - PG_HOST=postgres
    volumes:
      - ${PWD}:/code
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry
      - socket:/socket

volumes:
  cargogit: {}
  cargoregistry: {}
  socket: {}
