version: "3"

services:
  datadog-agent:
    image: docker.io/datadog/agent:7
    networks:
      - backend
    environment:
      - DD_API_KEY=${TEST_DATADOG_API_KEY}
      - DD_APM_ENABLED=false
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_LOGS_DD_URL=runner:8080
      - DD_LOGS_CONFIG_LOGS_NO_SSL=true
      - DD_LOGS_CONFIG_USE_HTTP=true
      - DD_HEALTH_PORT=8182
      - DD_CMD_PORT=5001
      - DD_USE_DOGSTATSD=false
    volumes:
      - ${PWD}/tests/data/datadog-agent/conf.yaml:/etc/datadog-agent/conf.d/test.d/conf.yaml
  datadog-trace-agent:
    # Using 7.31.0 image to have the ability mimic tracing lib using json
    image: docker.io/datadog/agent:7.31.0
    networks:
      - backend
    environment:
      - DD_API_KEY=${TEST_DATADOG_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_DD_URL=http://runner:8081
      - DD_HEALTH_PORT=8183
      - DD_CMD_PORT=5002
      - DD_USE_DOGSTATSD=false
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    hostname: runner
    networks:
      - backend
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "datadog-agent-integration-tests"
      - "--no-capture"
      - "--lib"
      - "sources::datadog::agent::integration_tests::"
    environment:
      - AGENT_ADDRESS=datadog-agent:8181
      - AGENT_HEALTH_ADDRESS=http://datadog-agent:8182
      - TRACE_AGENT_URL=http://datadog-trace-agent:8126/v0.4/traces
      - TRACE_AGENT_HEALTH_ADDRESS=http://datadog-trace-agent:8183
    depends_on:
      - datadog-agent
      - datadog-trace-agent
    volumes:
      - ${PWD}:/code
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

networks:
  backend: {}

volumes:
  cargogit: {}
  cargoregistry: {}
