version: "3"

services:
  squid:
    image: docker.io/babim/squid
    depends_on:
      - nginx-proxy
    networks:
      - public
      - proxy
  nginx:
    image: docker.io/nginx:1.19.4
    networks:
      - public
    volumes:
      - ${PWD}/tests/data/nginx/:/etc/nginx:ro
  nginx-proxy:
    image: docker.io/nginx:1.19.4
    networks:
      - proxy
    volumes:
      - ${PWD}/tests/data/nginx/:/etc/nginx:ro
  runner:
    build:
      context: ${PWD}
      dockerfile: scripts/integration/Dockerfile
      args:
        - RUST_VERSION=${RUST_VERSION}
    working_dir: /code
    command:
      - "cargo"
      - "nextest"
      - "run"
      - "--no-fail-fast"
      - "--no-default-features"
      - "--features"
      - "nginx-integration-tests"
      - "--lib"
      - "::nginx_metrics::"
      - "--"
      - "--nocapture"
    depends_on:
      - nginx
      - squid
    environment:
      - NGINX_ADDRESS=http://nginx:8000
      - NGINX_PROXY_ADDRESS=http://nginx-proxy:8000
      - SQUID_ADDRESS=http://squid:3128
    networks:
      - public
    volumes:
      - ${PWD}:/code
      - cargogit:/usr/local/cargo/git
      - cargoregistry:/usr/local/cargo/registry

networks:
  public: {}
  proxy: {}

volumes:
  cargogit: {}
  cargoregistry: {}
